Add missing IM endpoint to some of the requested commands. Update corrections in radl configuration and uncomment script block for testing.
Signed-off-by: Samuel Bernardo <samuel@lip.pt>

diff --git a/.sqa/config.yml b/.sqa/config.yml
--- a/.sqa/config.yml
+++ b/.sqa/config.yml
@@ -17,35 +17,35 @@ sqa_criteria:
       im:
         container: imclient
         commands:
-#          - |
-#            #!/bin/bash
-#            echo "Check auth.dat file:"
-#            ls -al "${IM_AUTH_FILE}"
-#            printf "$(cat /im/test.radl)" "${OPENSTACK_URL}" "${RADL_IMAGE_ID}" > /im/test-ost.radl
-#            echo "Printing radl file"
-#            cat /im/test-ost.radl
-#            echo 
-#            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/test-ost.radl > ./im_radl.json
-#            RETURN_CODE=$?
-#            echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
-#            echo "Infrastructure Manager output:"
-#            cat ./im_radl.json
-#            sed -i 1,1d ./im_radl.json
-#            INFID=$(jq -r '[ .infid ] | .[]' ./im_radl.json)
-#            echo "INFID=${INFID}"
-#            if [ ${RETURN_CODE} -eq 0 ] && ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
-#              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
-#              echo "im_client.py destroy return code: $?"
-#            elif ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
-#              echo "Deployment failed. Logs:"
-#              im_client.py -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
-#              echo 
-#              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
-#              echo "im_client.py destroy return code: $?"
-#              exit ${RETURN_CODE}
-#            else
-#              exit ${RETURN_CODE}
-#            fi
+          - |
+            #!/bin/bash
+            echo "Check auth.dat file:"
+            ls -al "${IM_AUTH_FILE}"
+            printf "$(cat /im/test.radl)" "${OPENSTACK_URL}" "${RADL_IMAGE_ID}" > /im/test-ost.radl
+            echo "Printing radl file"
+            cat /im/test-ost.radl
+            echo 
+            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/test-ost.radl > ./im_radl.json
+            RETURN_CODE=$?
+            echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
+            echo "Infrastructure Manager output:"
+            cat ./im_radl.json
+            awk "/\{/,/\}/ { print $1 }" ./im_radl.json > ./im_radl_aux.json
+            INFID=$(jq -r '[ .infid ] | .[]' ./im_radl_aux.json)
+            echo "INFID=${INFID}"
+            if [ ${RETURN_CODE} -eq 0 ] && ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
+              echo "im_client.py destroy return code: $?"
+            elif ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              echo "Deployment failed. Logs:"
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              echo 
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
+              echo "im_client.py destroy return code: $?"
+              exit ${RETURN_CODE}
+            else
+              exit ${RETURN_CODE}
+            fi
           - |
             #!/bin/bash
             printf "$(cat /im/tosca_create.yml)" "${OPENSTACK_URL}" "${TOSCA_IMAGE_ID}" "${OPENSTACK_URL}" "${TOSCA_IMAGE_ID}" > /im/tosca_create_with_image.yml
@@ -65,13 +65,13 @@ sqa_criteria:
             INFID=$(jq -r '[ .infid ] | .[]' ./im_tosca_aux.json)
             echo "INFID=${INFID}"
             if [ ${RETURN_CODE} -eq 0 ] && ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
-              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
               echo "im_client.py destroy return code: $?"
             elif ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
               echo "Deployment failed. Logs:"
-              im_client.py -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
               echo 
-              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
               echo "im_client.py destroy return code: $?"
               exit ${RETURN_CODE}
             else 
