Generate auth.dat at runtime
Signed-off-by: Samuel Bernardo <samuel@lip.pt>

diff --git a/.sqa/config.yml b/.sqa/config.yml
--- a/.sqa/config.yml
+++ b/.sqa/config.yml
@@ -5,9 +5,6 @@ config:
       - id: orviz-github-basic
         username_var: GIT_USER
         password_var: GIT_PASSWORD
-      - id: samuel-dockerhub
-        username_var: JPL_DOCKERUSER
-        password_var: JPL_DOCKERPASS
       - id: incd_openstack
         variable: OPENSTACK_URL
       - id: incd_openstack_id
@@ -26,48 +23,89 @@ sqa_criteria:
           - |
             #!/bin/bash
             printf "$(cat /im/auth/auth.dat)" "${IM_USER}" "${IM_PASS}" incd "https://${OPENSTACK_URL}" "${OPENSTACK_USER}" "${OPENSTACK_PASS}" eosc-synergy default > ${IM_AUTH_FILE}
-            printf "$(cat /im/test.radl)" "${OPENSTACK_URL}" "${IM_IMAGE_ID}" > ./test.radl
-            cp ./test.radl /im/test.radl
-          - |
-            #!/bin/bash
-            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/test.radl > ./im_radl.json
+            echo "Generated auth.dat file:"
+            ls -l ${IM_AUTH_FILE}
+            printf "$(cat /im/test.radl)" "${OPENSTACK_URL}" "${RADL_IMAGE_ID}" > /im/test-ost.radl
+            echo "Printing radl file"
+            cat /im/test-ost.radl
+            echo 
+            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/test-ost.radl > ./im_radl.json
             RETURN_CODE=$?
             echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
             echo "Infrastructure Manager output:"
             cat ./im_radl.json
-            if [ ${RETURN_CODE} -eq 0 ]; then
-              INFID=$(jq -r '[ .infid ] | .[]'  ./im_radl.json)
-              echo "INFID=${INFID}"
-              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
+            awk "/\{/,/\}/ { print $1 }" ./im_radl.json > ./im_radl_aux.json
+            echo "Infrastructure Manager output (only json part):"
+            cat ./im_radl_aux.json
+            echo 
+            INFID=$(jq -r '[ .infid ] | .[]' ./im_radl_aux.json)
+            echo "INFID=${INFID}"
+            if [ ${RETURN_CODE} -eq 0 ] && ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              echo "Deployment finished with success. Logs:"
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              echo 
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
               echo "im_client.py destroy return code: $?"
+            elif ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              echo "Deployment failed. Logs:"
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              echo 
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
+              echo "im_client.py destroy return code: $?"
+              exit ${RETURN_CODE}
             else
               exit ${RETURN_CODE}
             fi
           - |
             #!/bin/bash
-            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/tosca_create.yml > ./im_tosca.json
+            printf "$(cat /im/auth/auth.dat)" "${IM_USER}" "${IM_PASS}" incd "https://${OPENSTACK_URL}" "${OPENSTACK_USER}" "${OPENSTACK_PASS}" eosc-synergy default > ${IM_AUTH_FILE}
+            echo "Generated auth.dat file:"
+            ls -l ${IM_AUTH_FILE}
+            printf "$(cat /im/tosca_create.yml)" "${OPENSTACK_URL}" "${TOSCA_IMAGE_ID}" "${OPENSTACK_URL}" "${TOSCA_IMAGE_ID}" > /im/tosca_create_with_image.yml
+            echo "Printing TOSCA file"
+            cat /im/tosca_create_with_image.yml
+            echo 
+            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/tosca_create_with_image.yml > ./im_tosca.json
             RETURN_CODE=$?
             echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
             echo "Infrastructure Manager output:"
-            cat ./im_radl.json
-            if [ ${RETURN_CODE} -eq 0 ]; then
-              INFID=$(jq -r '[ .infid ] | .[]'  ./im_tosca.json)
-              echo "INFID=${INFID}"
-              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
+            cat ./im_tosca.json
+            echo 
+            awk "/\{/,/\}/ { print $1 }" ./im_tosca.json > ./im_tosca_aux.json
+            echo "Infrastructure Manager output (only json part):"
+            cat ./im_tosca_aux.json
+            echo 
+            INFID=$(jq -r '[ .infid ] | .[]' ./im_tosca_aux.json)
+            echo "INFID=${INFID}"
+            if [ ${RETURN_CODE} -eq 0 ] && ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              echo "Deployment finished with success. Logs:"
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              echo 
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
               echo "im_client.py destroy return code: $?"
-            else
+            elif ! [[ -z "${INFID}" && "x${INFID}x" == "xnullx" ]]; then
+              echo "Deployment failed. Logs:"
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
+              echo 
+              im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" destroy ${INFID}
+              echo "im_client.py destroy return code: $?"
+              exit ${RETURN_CODE}
+            else 
               exit ${RETURN_CODE}
             fi
 
 environment:
-  IM_AUTH_FILE: "/im/auth.dat"
-  IM_IMAGE_ID: "4266a328-0c0e-4aa7-9087-b868882d39cb"
+  RADL_IMAGE_ID: "5336f60b-d4cc-4285-a573-1b706cbbe40b"
+  TOSCA_IMAGE_ID: "97624935-200f-4670-9ea8-c65282adbe56"
   IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im/"
-  JPL_DOCKERPUSH: "imclient"
+  OPENSTACK_ID_PORT: "5000"
+  IM_AUTH_FILE: '/im/auth/auth.dat'
+  #JPL_DOCKERPUSH: "imclient"
   #JPL_IGNOREFAILURES: "defined"
   #JPL_DOCKERFORCEBUILD: "enabled"
   #JPL_WORKSPACEDEBUG: "true"
-  #JPL_WORKSPACEDEBUGTIMEOUT: 45
+  #JPL_WORKSPACEDEBUGTIMEOUT: "45"
+  #JPL_DEBUG: "true"
 
 # Timeout after no activity in logs for this configuration (not the absolute duration)
-#timeout: 1200
+timeout: 1800
